# Generated by Django 4.2.9 on 2024-05-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='icon',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='icon',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon',
            field=models.TextField(null=True),
        ),
    ]
