# Generated by Django 4.2.9 on 2024-05-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_currency_icon_alter_network_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='uid',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='uid',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
