# Generated by Django 4.2.9 on 2024-05-24 15:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_network_uid_paymentmethod_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='costs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), null=True, size=None),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='explorer',
            field=models.TextField(null=True),
        ),
    ]
