# Generated by Django 4.2.9 on 2024-05-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_paymentmethod_category_paymentmethod_costs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='sub',
            field=models.TextField(null=True),
        ),
    ]
