# Generated by Django 4.2.9 on 2024-05-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_paymentmethod_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
