# Generated by Django 4.2.9 on 2024-05-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_network_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128, unique=True)),
                ('cost', models.FloatField()),
                ('is_percents', models.BooleanField()),
                ('cur', models.CharField(db_index=True, max_length=12)),
            ],
        ),
    ]
