# Generated by Django 4.2.9 on 2024-05-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('cur', models.CharField(db_index=True, max_length=8)),
                ('method', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='direction',
            name='dest',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='direction',
            name='src',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='direction',
            unique_together={('src', 'dest')},
        ),
    ]
