# Generated by Django 4.2.9 on 2024-05-24 23:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_remove_paymentmethod_costs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='costs',
        ),
        migrations.AddField(
            model_name='payment',
            name='costs_income',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='payment',
            name='costs_outcome',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
