# Generated by Django 4.2.9 on 2024-05-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_remove_direction_costs_payment_costs_income_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.JSONField()),
            ],
        ),
    ]
