# Generated by Django 4.2.9 on 2024-05-25 23:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_appsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='costs_income',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_index=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='payment',
            name='costs_outcome',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_index=True, default=list, null=True, size=None),
        ),
    ]
