# Generated by Django 4.2.9 on 2024-05-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0014_alter_payment_costs_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='limits',
            field=models.JSONField(null=True),
        ),
    ]
