# Generated by Django 4.2.9 on 2024-06-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0015_correction_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=36)),
                ('image', models.BinaryField()),
                ('remove_after', models.FloatField(null=True)),
            ],
        ),
    ]
