# Generated by Django 4.2.9 on 2024-06-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0016_kycphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycphoto',
            name='mine_type',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='kycphoto',
            name='uid',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
