# Generated by Django 4.2.9 on 2024-06-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0017_kycphoto_mine_type_kycphoto_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycphoto',
            old_name='mine_type',
            new_name='mime_type',
        ),
    ]
