# Generated by Django 4.2.9 on 2024-06-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0018_rename_mine_type_kycphoto_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycphoto',
            name='uid',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='kycphoto',
            unique_together={('uid', 'type')},
        ),
    ]
