# Generated by Django 4.2.9 on 2024-06-04 21:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0019_alter_kycphoto_uid_alter_kycphoto_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_index=True, default=list, null=True, size=None),
        ),
    ]
