# Generated by Django 4.2.9 on 2024-06-04 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0021_account_created_at_account_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(db_index=True, max_length=256)),
                ('provider', models.CharField(db_index=True, max_length=36)),
                ('image_b64_document', models.BinaryField()),
                ('image_b64_selfie', models.BinaryField()),
                ('verified_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='exchange.account')),
            ],
            options={
                'unique_together': {('document_id', 'provider')},
            },
        ),
    ]
