# Generated by Django 4.2.9 on 2024-06-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0023_alter_kyc_image_b64_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
