# Generated by Django 4.2.9 on 2024-06-21 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0025_account_is_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_b64', models.BinaryField(null=True)),
                ('attrs', models.JSONField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='exchange.account')),
            ],
        ),
    ]
