# Generated by Django 4.2.9 on 2024-06-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0026_organizationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdocument',
            name='type',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
