# Generated by Django 4.2.9 on 2024-06-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0027_organizationdocument_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
