# Generated by Django 4.2.9 on 2024-07-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0028_direction_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('icon', models.TextField(null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=64, null=True)),
                ('explorer', models.TextField(null=True)),
                ('sub', models.TextField(null=True)),
            ],
        ),
    ]
