# Generated by Django 4.2.9 on 2024-07-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0029_cashmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(db_index=True, max_length=128)),
                ('schema', models.JSONField()),
                ('payload', models.JSONField()),
                ('ttl', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128, unique=True)),
                ('class_name', models.CharField(db_index=True, max_length=128)),
                ('account_uid', models.CharField(db_index=True, max_length=128)),
                ('last_access_utc', models.DateTimeField(db_index=True)),
                ('kill_after_utc', models.DateTimeField(db_index=True, null=True)),
            ],
        ),
    ]
