# Generated by Django 4.2.9 on 2024-07-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0030_credential_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='account_uid',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
    ]
