# Generated by Django 4.2.9 on 2024-07-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0031_credential_account_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='merchant_meta',
            field=models.JSONField(null=True),
        ),
    ]
