# Generated by Django 4.2.9 on 2024-07-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0032_account_merchant_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='payload',
            field=models.JSONField(db_index=True),
        ),
    ]
