# Generated by Django 4.2.9 on 2024-07-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0033_alter_credential_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='account_uid',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
    ]
