# Generated by Django 4.2.9 on 2024-07-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0035_storageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageitem',
            name='storage_id',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
