# Generated by Django 4.2.9 on 2024-07-28 20:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0036_alter_storageitem_storage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitem',
            name='storage_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), db_index=True, null=True, size=None),
        ),
    ]
