# Generated by Django 4.2.9 on 2024-07-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0037_storageitem_storage_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitem',
            name='signature',
            field=models.CharField(db_index=True, max_length=512, null=True),
        ),
    ]
