# Generated by Django 4.2.9 on 2024-08-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0039_masspaymentbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageitem',
            name='category',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='storage_id',
            field=models.CharField(db_index=True, max_length=512, null=True),
        ),
    ]
