# Generated by Django 4.2.9 on 2024-09-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0040_alter_storageitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='merchant_meta',
            field=models.JSONField(db_index=True, null=True),
        ),
    ]
