# Generated by Django 4.2.9 on 2024-12-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0041_alter_account_merchant_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='inn',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
