# Generated by Django 4.2.9 on 2024-12-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0042_kyc_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='source',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
