# Generated by Django 4.2.9 on 2024-12-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0043_kyc_source'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kyc',
            unique_together=set(),
        ),
    ]
