# Generated by Django 4.2.9 on 2024-12-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0044_alter_kyc_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verified',
            field=models.JSONField(null=True),
        ),
    ]
