# Generated by Django 4.2.9 on 2025-01-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0046_kyc_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='owner_did',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
    ]
