# Generated by Django 4.2.9 on 2025-01-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0047_direction_owner_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='code',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
    ]
