# Generated by Django 4.2.9 on 2025-01-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0048_network_code_paymentmethod_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmethod',
            name='code',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
    ]
