# Generated by Django 4.2.9 on 2025-01-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0049_cashmethod_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmethod',
            name='owner_did',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='owner_did',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='owner_did',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='owner_did',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
    ]
