# Generated by Django 4.2.9 on 2025-01-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0050_cashmethod_owner_did_currency_owner_did_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='owner_did',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
    ]
