# Generated by Django 4.2.9 on 2025-01-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0051_payment_owner_did'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('symbol', 'owner_did')},
        ),
    ]
