name: Public docker images

on:
  release:
    types: [ created ]

jobs:
  backend:
    runs-on: ubuntu-latest
    # if: github.event.release.name == 'backend'
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: purik/ruswift:latest
